/-
Copyright (c) 2026 Laurent Bartholdi. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Laurent Bartholdi, based on code by ChatGPT 5.6 Sol
-/

import Mathlib.Algebra.Lie.Quotient
import Mathlib.Algebra.Lie.Semisimple.Defs
import Mathlib.LinearAlgebra.FiniteDimensional.Basic

/-!
# Elementary classes of Lie algebras

This file packages Lie algebras in a fixed universe and defines the
elementary hierarchy generated by finite-dimensional and Abelian Lie
algebras under extensions and directed unions.
-/

namespace HopfAmenability

noncomputable section

universe u v w

/-- A bundled Lie algebra over `k`.  This small project-local bundle is used
only to state closure constructions whose constituents have different
underlying types. -/
structure LieAlgebraObject (k : Type u) [Field k] where
  Carrier : Type v
  lieRing : LieRing Carrier
  lieAlgebra : LieAlgebra k Carrier

attribute [instance] LieAlgebraObject.lieRing LieAlgebraObject.lieAlgebra

/-- Bundle an already-instanced Lie algebra. -/
def LieAlgebraObject.of (k : Type u) [Field k] (L : Type v)
    [LieRing L] [LieAlgebra k L] :
  LieAlgebraObject k where
  Carrier := L
  lieRing := inferInstance
  lieAlgebra := inferInstance

variable {k : Type u} [Field k]

/-- The Lie algebra carried by a Lie ideal. -/
def LieAlgebraObject.ofIdeal (A : LieAlgebraObject k)
    (I : LieIdeal k A.Carrier) : LieAlgebraObject k :=
  LieAlgebraObject.of k I

/-- The quotient Lie algebra by a Lie ideal. -/
def LieAlgebraObject.quotient (A : LieAlgebraObject k)
    (I : LieIdeal k A.Carrier) : LieAlgebraObject k :=
  LieAlgebraObject.of k (A.Carrier ⧸ I)

/-- The Lie algebra carried by a Lie subalgebra. -/
def LieAlgebraObject.ofSubalgebra (A : LieAlgebraObject k)
    (S : LieSubalgebra k A.Carrier) : LieAlgebraObject k :=
  LieAlgebraObject.of k S

/-- The canonical quotient map by a Lie ideal as a Lie homomorphism. -/
def LieIdeal.quotientMkLieHom {L : Type v} [LieRing L] [LieAlgebra k L]
    (I : LieIdeal k L) : LieHom k L (L ⧸ I) where
  __ := I.toSubmodule.mkQ
  map_lie' := fun {_ _} => rfl

@[simp]
theorem LieIdeal.quotientMkLieHom_apply {L : Type v}
    [LieRing L] [LieAlgebra k L] (I : LieIdeal k L) (x : L) :
    LieIdeal.quotientMkLieHom I x = LieSubmodule.Quotient.mk x :=
  rfl

theorem LieIdeal.quotientMkLieHom_surjective {L : Type v}
    [LieRing L] [LieAlgebra k L] (I : LieIdeal k L) :
    Function.Surjective (LieIdeal.quotientMkLieHom I) :=
  Submodule.Quotient.mk_surjective I.toSubmodule

theorem LieIdeal.quotientMkLieHom_injective_of_eq_bot {L : Type v}
    [LieRing L] [LieAlgebra k L] (I : LieIdeal k L) (hI : I = ⊥) :
    Function.Injective (LieIdeal.quotientMkLieHom I) := by
  intro x y hxy
  have hzero : LieIdeal.quotientMkLieHom I (x - y) = 0 := by
    rw [map_sub, hxy, sub_self]
  have hmem : x - y ∈ I := by
    exact LieSubmodule.Quotient.mk_eq_zero'.mp hzero
  rw [hI] at hmem
  change x - y = 0 at hmem
  exact sub_eq_zero.mp hmem

/-- Quotienting by the zero ideal does not change a Lie algebra. -/
noncomputable def LieIdeal.quotientEquivOfEqBot {L : Type v}
    [LieRing L] [LieAlgebra k L] (I : LieIdeal k L) (hI : I = ⊥) :
    LieEquiv k (L ⧸ I) L :=
  (LieEquiv.ofBijective (LieIdeal.quotientMkLieHom I)
    ⟨LieIdeal.quotientMkLieHom_injective_of_eq_bot I hI,
      LieIdeal.quotientMkLieHom_surjective I⟩).symm

/-- A finite subset of a directed union is contained in one member. -/
theorem exists_directed_member_containing_finset
    {L : Type v} [LieRing L] [LieAlgebra k L]
    {ι : Type w} [Nonempty ι] (S : ι → LieSubalgebra k L)
    (hdir : Directed (· ≤ ·) S) (s : Finset L)
    (hs : ∀ x ∈ s, ∃ i, x ∈ S i) :
    ∃ i, ∀ x ∈ s, x ∈ S i := by
  classical
  induction s using Finset.induction_on with
  | empty =>
      exact ⟨Classical.choice inferInstance, by simp⟩
  | @insert x s hxs ih =>
      obtain ⟨ix, hix⟩ := hs x (by simp)
      obtain ⟨is, his⟩ := ih (fun y hy => hs y (by simp [hy]))
      obtain ⟨i, hxi, hsi⟩ := hdir ix is
      refine ⟨i, ?_⟩
      intro y hy
      rw [Finset.mem_insert] at hy
      rcases hy with rfl | hy
      · exact hxi hix
      · exact hsi (his y hy)

/-- Membership in a directed supremum of Lie subalgebras is membership in
one member of the family. -/
theorem LieSubalgebra.mem_iSup_of_directed
    {L : Type v} [LieRing L] [LieAlgebra k L]
    {ι : Type w} [Nonempty ι] (S : ι → LieSubalgebra k L)
    (hdir : Directed (· ≤ ·) S) {x : L} :
    x ∈ iSup S ↔ ∃ i, x ∈ S i := by
  let U : LieSubalgebra k L := {
    __ := iSup fun i => (S i).toSubmodule
    lie_mem' := by
      intro y z hy hz
      change y ∈ iSup (fun i => (S i).toSubmodule) at hy
      change z ∈ iSup (fun i => (S i).toSubmodule) at hz
      change Bracket.bracket y z ∈ iSup (fun i => (S i).toSubmodule)
      rw [Submodule.mem_iSup_of_directed _ hdir] at hy hz ⊢
      obtain ⟨i, hi⟩ := hy
      obtain ⟨j, hj⟩ := hz
      obtain ⟨l, hil, hjl⟩ := hdir i j
      exact ⟨l, (S l).lie_mem (hil hi) (hjl hj)⟩ }
  have hU : U = iSup S := by
    apply le_antisymm
    · intro y hy
      change y ∈ iSup (fun i => (S i).toSubmodule) at hy
      rw [Submodule.mem_iSup_of_directed _ hdir] at hy
      obtain ⟨i, hi⟩ := hy
      exact (le_iSup S i) hi
    · apply iSup_le
      intro i y hy
      change y ∈ iSup (fun i => (S i).toSubmodule)
      exact (le_iSup (fun i => (S i).toSubmodule) i) hy
  rw [← hU]
  change x ∈ iSup (fun i => (S i).toSubmodule) ↔ _
  exact Submodule.mem_iSup_of_directed _ hdir

/-- The inductively generated class `EL` from the article.  Trivial
extensions are harmless; the constructors work with an ideal and its
canonical quotient, while directed unions are expressed by a directed
family whose supremum is the whole algebra. -/
inductive IsElementaryLieObject : LieAlgebraObject k → Prop
  | finiteDimensional (A : LieAlgebraObject k)
      (hA : FiniteDimensional k A.Carrier) : IsElementaryLieObject A
  | abelian (A : LieAlgebraObject k) (hA : IsLieAbelian A.Carrier) :
      IsElementaryLieObject A
  | extension (A : LieAlgebraObject k) (I : LieIdeal k A.Carrier)
      (hI : IsElementaryLieObject (A.ofIdeal I))
      (hQ : IsElementaryLieObject (A.quotient I)) :
      IsElementaryLieObject A
  | directedUnion (A : LieAlgebraObject k) (ι : Type v) [Nonempty ι]
      (S : ι → LieSubalgebra k A.Carrier)
      (hdir : Directed (· ≤ ·) S)
      (hsup : @iSup _ _ CompleteLattice.toSupSet S = ⊤)
      (hS : ∀ i, IsElementaryLieObject (A.ofSubalgebra (S i))) :
      IsElementaryLieObject A

/-- An unbundled Lie algebra is elementarily amenable when its bundled
object belongs to the inductively generated elementary class. -/
def IsElementarilyAmenableLieAlgebra (L : Type v)
    [LieRing L] [LieAlgebra k L] : Prop :=
  IsElementaryLieObject.{u, v, v} (LieAlgebraObject.of k L)

/-- Finite generation as a Lie algebra. -/
def IsFinitelyGeneratedLieAlgebra (L : Type v)
    [LieRing L] [LieAlgebra k L] : Prop :=
  ∃ s : Finset L, LieSubalgebra.lieSpan k L (s : Set L) = ⊤

/-- A class of Lie algebras containing the elementary generators and closed
under the two elementary constructions. -/
structure ElementaryClosedLieClass where
  universeWitness : Type v
  mem : LieAlgebraObject.{u, v} k → Prop
  finiteDimensional_mem : ∀ (A : LieAlgebraObject.{u, v} k),
    FiniteDimensional k A.Carrier → mem A
  abelian_mem : ∀ (A : LieAlgebraObject.{u, v} k),
    IsLieAbelian A.Carrier → mem A
  extension_mem : ∀ (A : LieAlgebraObject.{u, v} k)
      (I : LieIdeal k A.Carrier),
    mem (A.ofIdeal I) → mem (A.quotient I) → mem A
  directedUnion_mem : ∀ (A : LieAlgebraObject.{u, v} k)
      (ι : Type v) [Nonempty ι]
      (S : ι → LieSubalgebra k A.Carrier),
    Directed (· ≤ ·) S → iSup S = ⊤ →
      (∀ i, mem (A.ofSubalgebra (S i))) → mem A

/-- The elementary class is contained in every class with the defining
closure properties. -/
theorem IsElementaryLieObject.mem_closedClass
    {A : LieAlgebraObject.{u, v} k}
    (C : ElementaryClosedLieClass (k := k))
    (hA : IsElementaryLieObject.{u, v, v} A) :
    C.mem A := by
  induction hA with
  | finiteDimensional A hA => exact C.finiteDimensional_mem A hA
  | abelian A hA => exact C.abelian_mem A hA
  | extension A I hI hQ ihI ihQ => exact C.extension_mem A I ihI ihQ
  | directedUnion A ι S hdir hsup hS ihS =>
      exact C.directedUnion_mem A ι S hdir hsup ihS

end

end HopfAmenability
